[package]
name = "rusty-robot-drivers"
version = "0.1.0"
license = "Apache-2.0"
edition = "2024"

[dependencies]
# imu-traits = "*"  unusable as it requires std dependencies
nmea = { version = "*", default-features = false } # GPS sentence parsing support